// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package postgresdb

import (
	"time"

	"github.com/google/uuid"
)

type Outlet struct {
	ID uuid.UUID `json:"id"`
	// one user one outlet
	User     uuid.UUID `json:"user"`
	Deposit  int64     `json:"deposit"`
	IsActive bool      `json:"is_active"`
}

type Product struct {
	ProductCode     string `json:"product_code"`
	ProductName     string `json:"product_name"`
	ProductEndpoint string `json:"product_endpoint"`
}

type RequestLog struct {
	ID uuid.UUID `json:"id"`
	// inq or pay
	Mode           string `json:"mode"`
	Product        string `json:"product"`
	BillNumber     int64  `json:"bill_number"`
	Name           string `json:"name"`
	TotalAmount    int64  `json:"total_amount"`
	BillerResponse string `json:"biller_response"`
	// user who request the bill
	Outlet    uuid.UUID `json:"outlet"`
	CreatedAt time.Time `json:"created_at"`
}

type Transaction struct {
	ID                  uuid.UUID     `json:"id"`
	BillNumber          string        `json:"bill_number"`
	Product             string        `json:"product"`
	TransactionDatetime time.Time     `json:"transaction_datetime"`
	Inquiry             uuid.NullUUID `json:"inquiry"`
	Payment             uuid.NullUUID `json:"payment"`
	Amount              int64         `json:"amount"`
	RefferenceNumber    string        `json:"refference_number"`
	// user who pay the bill
	Outlet uuid.UUID `json:"outlet"`
	// -1:failed;0:pending;1:success
	Status int32 `json:"status"`
}
