// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: product.sql

package postgresdb

import (
	"context"
)

const getProductByCode = `-- name: GetProductByCode :one
SELECT product_code, product_name, product_endpoint FROM products
WHERE product_code = $1 LIMIT 1
`

func (q *Queries) GetProductByCode(ctx context.Context, productCode string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByCode, productCode)
	var i Product
	err := row.Scan(&i.ProductCode, &i.ProductName, &i.ProductEndpoint)
	return i, err
}
